repos:
  - repo: https://github.com/astro/deadnix
    rev: da39a3ee5e6b4b0d3255bfef95601890afd80709  # frozen: v1.2.3
    hooks:
      - id: deadnix
        args: [--edit] # Uncomment to automatically modify files
        stages: [commit]
